image: dockerproxy-cwfr1.rd.francetelecom.fr/golang:latest

variables:
  DEP_VERSION: 0.3.2

job:
  before_script:
    # Download the binary to bin folder in $GOPATH
    - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
    # Make the binary executable
    - chmod +x $GOPATH/bin/dep
    - go get -u golang.org/x/lint/golint

  script:
    - dep ensure
    - make check race release
