image: dockerproxy-cwfr1.rd.francetelecom.fr/golang:latest

# Secret variables stored on Gitlab CI:
# VRA_KEY, VRA_SECRET, THE_PROXY

variables:
  GO111MODULE: auto
  ## For now, I disabled 'GO111MODULE=on go get' because:
  ##     https://github.com/DHowett/go-plist/issues/40
  ## For now, I stick with 'dep ensure'
  # With TF_ACC=1, 'go test' will create actual resources on BRMC
  TF_ACC: 1

job:
  # innovation necessary for getting internet access (through transparent proxying)
  # http://devops-store.rd.francetelecom.fr/en/dos?page_id=6538.
  # Tags: docker, shared, innovation
  # For now, I use Jerome Simon's private runner.
  tags: [docker, rsc]
  before_script:
    - export http_proxy=$THE_PROXY https_proxy=$THE_PROXY HTTP_PROXY=$THE_PROXY HTTPS_PROXY=$THE_PROXY
    - export https_proxy=$THE_PROXY
    - curl google.fr
    - git config --global http.proxy $THE_PROXY
    - git config --global https.proxy $THE_PROXY
    # First, make sure our project is in GOPATH, otherwise
    # we are going to hit a 'cannot determine module path for source directory'
    - export CI_PROJECT_DIR=${GOPATH}/src/${CI_PROJECT_URL/http?:\/\//}
    - rm -Rf $CI_PROJECT_DIR && mkdir -p $CI_PROJECT_DIR && cp -r $PWD/. $CI_PROJECT_DIR && cd $CI_PROJECT_DIR

    - go get -u github.com/golang/dep/cmd/dep
    - go get -u golang.org/x/lint/golint

  script:
    - dep ensure
    - go test ./... -run BRMC
    # - make check
    # - make race release
