image: dockerproxy-cwfr1.rd.francetelecom.fr/golang:latest

variables:
  GO111MODULE: on

job:
  # innovation necessary for getting internet access (through transparent proxying)
  # http://devops-store.rd.francetelecom.fr/en/dos?page_id=6538
  tags: [docker, shared, innovation]
  before_script:
    - go get -u golang.org/x/lint/golint
    - CI_PROJECT_DIR=/go/src/${CI_PROJECT_URL/http?:\/\//}
    - mkdir -p $CI_PROJECT_DIR
    - mv $PWD/{*,.*} $CI_PROJECT_DIR
    - cd $CI_PROJECT_DIR

  script:
    - go get
    - make check race release
