image: dockerproxy-cwfr1.rd.francetelecom.fr/golang:latest

variables:
  DEP_VERSION: 0.3.2

job:
  # innovation necessary for getting internet access (through transparent proxying)
  # http://devops-store.rd.francetelecom.fr/en/dos?page_id=6538
  tags: [docker, shared, innovation]
  before_script:
    # Download the binary to bin folder in $GOPATH
    - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 > $GOPATH/bin/dep
    - sha256sum -c <<< "322152b8b50b26e5e3a7f6ebaeb75d9c11a747e64bbfd0d8bb1f4d89a031c2b5  $GOPATH/bin/dep"
    # Make the binary executable
    - chmod +x $GOPATH/bin/dep
    - go get -u golang.org/x/lint/golint

  script:
    - dep ensure
    - make check race release
