image: dockerproxy-cwfr1.rd.francetelecom.fr/golang:latest

# Secret variables stored on Gitlab CI:
# VRA_KEY, VRA_SECRET

variables:
  GO111MODULE: on
  TF_ACC: 1 # WARNING: 'go test' will create actual resources on BRMC

job:
  # innovation necessary for getting internet access (through transparent proxying)
  # http://devops-store.rd.francetelecom.fr/en/dos?page_id=6538
  tags: [docker, shared, innovation]
  before_script:
    - go get -u golang.org/x/lint/golint
    - CI_PROJECT_DIR=/go/src/${CI_PROJECT_URL/http?:\/\//}
    - mkdir -p $CI_PROJECT_DIR
    - mv $PWD/{*,.*} $CI_PROJECT_DIR
    - cd $CI_PROJECT_DIR

  script:
    - go get
    - go install
    - go
    - go test ./... -run ^BRMC$
    # - make check
    # - make race release
